
CREATE TABLE t_p25425030_parking_challenge_ga.rooms (
  id VARCHAR(36) PRIMARY KEY,
  status VARCHAR(16) NOT NULL DEFAULT 'waiting',
  round INTEGER NOT NULL DEFAULT 0,
  phase VARCHAR(16) NOT NULL DEFAULT 'driving',
  timer_end BIGINT NOT NULL DEFAULT 0,
  spots_json TEXT NOT NULL DEFAULT '[]',
  created_at BIGINT NOT NULL DEFAULT 0,
  started_at BIGINT NOT NULL DEFAULT 0,
  max_players INTEGER NOT NULL DEFAULT 10
);

CREATE TABLE t_p25425030_parking_challenge_ga.room_players (
  room_id VARCHAR(36) NOT NULL,
  player_id VARCHAR(64) NOT NULL,
  name VARCHAR(32) NOT NULL,
  emoji VARCHAR(8) NOT NULL DEFAULT '🚗',
  color VARCHAR(16) NOT NULL DEFAULT '#FF2D55',
  body_color VARCHAR(16) NOT NULL DEFAULT '#CC0033',
  x FLOAT NOT NULL DEFAULT 400,
  y FLOAT NOT NULL DEFAULT 300,
  angle FLOAT NOT NULL DEFAULT 0,
  speed FLOAT NOT NULL DEFAULT 0,
  hp FLOAT NOT NULL DEFAULT 100,
  max_hp FLOAT NOT NULL DEFAULT 100,
  orbit_angle FLOAT NOT NULL DEFAULT 0,
  orbit_radius FLOAT NOT NULL DEFAULT 270,
  parked BOOLEAN NOT NULL DEFAULT FALSE,
  park_spot INTEGER NOT NULL DEFAULT -1,
  eliminated BOOLEAN NOT NULL DEFAULT FALSE,
  is_bot BOOLEAN NOT NULL DEFAULT FALSE,
  last_seen BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (room_id, player_id)
);
